# Generated by Django 3.1.7 on 2021-03-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='abi',
        ),
    ]
